# version 속성은 Docker Compose v2에서 더 이상 필요하지 않습니다

services:
  # FastAPI 백엔드 서버 (RDS 연결)
  fastapi:
    build: ./backend
    container_name: carfin_fastapi
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+asyncpg://carfin_admin:carfin_secure_password_2025@carfin-db.cbkayiqs4div.ap-northeast-2.rds.amazonaws.com:5432/carfin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512m"

# 프론트엔드는 별도로 개발하므로 제거

# PostgreSQL 볼륨은 RDS 사용으로 더 이상 필요없음
# volumes:
#   postgres_data:
#     driver: local

networks:
  default:
    name: carfin_network
    driver: bridge