name: Deploy to AWS

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: ECR_REGISTRY,ECR_REPOSITORY,AWS_REGION
          script: |
            set -e  # 에러 발생 시 스크립트 중단
            cd ~/CarFin
            
            # ECR 로그인 (EC2 IAM Role 자동 사용)
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
            
            # 기존 컨테이너 및 볼륨 완전히 제거
            DOCKER_IMAGE=${ECR_REGISTRY}/${ECR_REPOSITORY}:latest docker-compose down -v
            
            # 기존 이미지도 삭제
            docker rmi ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest || true
            
            # 새 이미지 pull
            DOCKER_IMAGE=${ECR_REGISTRY}/${ECR_REPOSITORY}:latest docker-compose pull
            
            # 컨테이너 새로 시작 (ECR 이미지 사용)
            DOCKER_IMAGE=${ECR_REGISTRY}/${ECR_REPOSITORY}:latest docker-compose up -d
            
            # Docker 로그아웃 (보안을 위해)
            docker logout ${ECR_REGISTRY}
            
            # 사용하지 않는 이미지 정리
            docker image prune -f

